### ISSUE TITLE
blog throws an error instead of telling me that im not supposed to post in cpp's blog

### ISSUE THREAD

**Issue by Ucaninek** [CPlusPatch/cpluspatch-cms-next#6]
reproduction steps:
1- log in with github
2- go to blog
3- click new post
4- _voila!_

![image](https://user-images.githubusercontent.com/43094930/183491187-fbe09662-bb7d-480d-ac25-f81158901920.png)

**Comment by CPlusPatch** [comment]
Fixed, closing now
